from __future__ import annotations

ERROR_MESSAGES = {
    "ENV_MISSING": "La configuracion del servicio esta incompleta.",
    "DATABASE_UNAVAILABLE": "La base de datos no esta disponible.",
    "REDIS_UNAVAILABLE": "Redis no esta disponible.",
    "PLATFORM_EMERGENCY_MODE_ACTIVE": "NODO esta en modo emergencia. Intenta nuevamente cuando el servicio se estabilice.",
    "MIGRATION_FAILED": "No se pudo aplicar la migracion.",
    "TELEGRAM_INIT_DATA_INVALID": "No pudimos validar tu sesion de Telegram.",
    "TELEGRAM_INIT_DATA_EXPIRED": "Tu sesion de Telegram expiro. Reabre la Mini App.",
    "USER_SUSPENDED": "Esta cuenta no puede operar en este momento.",
    "USER_NOT_FOUND": "No encontramos el usuario solicitado.",
    "SESSION_EXPIRED": "Tu sesion expiro. Vuelve a iniciar sesion.",
    "UNAUTHENTICATED": "Necesitas iniciar sesion.",
    "ADMIN_LOGIN_INVALID": "Usuario o clave invalida.",
    "RATE_LIMITED": "Demasiados intentos. Intenta nuevamente en un momento.",
    "VALIDATION_ERROR": "Revisa los datos enviados.",
    "PAGINATION_CURSOR_INVALID": "El cursor de paginacion no es valido.",
    "FORBIDDEN": "No tienes permiso para realizar esta accion.",
    "BUSINESS_NOT_FOUND": "No encontramos el negocio solicitado.",
    "ADMIN_BUSINESS_SEARCH_QUERY_TOO_SHORT": "Busca por ID de negocio o por al menos 3 caracteres del nombre.",
    "BUSINESS_ALREADY_EXISTS": "Ya existe un negocio activo para este usuario.",
    "BUSINESS_ALREADY_SUBMITTED": "Ya existe una verificacion pendiente para este negocio.",
    "BUSINESS_STATUS_INVALID": "El estado del negocio no permite esta accion.",
    "BUSINESS_VERIFICATION_REQUIRED": "Completa los datos de verificacion requeridos.",
    "BUSINESS_DOCUMENT_REQUIRED": "Debes cargar los documentos requeridos.",
    "BUSINESS_DOCUMENT_INVALID": "El documento no cumple los requisitos.",
    "BUSINESS_DOCUMENT_NOT_FOUND": "No encontramos el documento solicitado.",
    "ADMIN_REASON_REQUIRED": "Debes indicar una razon de revision.",
    "IDEMPOTENCY_KEY_REQUIRED": "Debes enviar una llave de idempotencia.",
    "IDEMPOTENCY_PAYLOAD_MISMATCH": "La llave de idempotencia ya fue usada con otro payload.",
    "STORAGE_UNAVAILABLE": "El almacenamiento privado no esta disponible.",
    "AD_NOT_FOUND": "No encontramos el anuncio solicitado.",
    "AD_NOT_AVAILABLE": "Este anuncio no esta disponible.",
    "AD_STATUS_INVALID": "El estado del anuncio no permite esta accion.",
    "AD_AMOUNT_RANGE_INVALID": "Revisa el rango del anuncio.",
    "AD_AMOUNT_TOO_HIGH": "Ese monto no esta disponible en el MVP.",
    "AD_OVERLAP_NOT_ALLOWED": "Ya existe un anuncio activo para ese rango.",
    "AD_LIMIT_NOT_ALLOWED": "Revisa el monto disponible y los anuncios activos del negocio.",
    "BUSINESS_NOT_APPROVED": "El negocio debe estar aprobado para publicar anuncios.",
    "BUSINESS_PUBLICATION_TEMPORARILY_UNAVAILABLE": "Publicacion temporalmente no disponible. Podras intentar nuevamente en unos minutos.",
    "BUSINESS_PUBLICATION_UNDER_REVIEW": "Publicacion temporalmente no disponible mientras se revisa la operacion.",
    "BUSINESS_PUBLICATION_HOLD_NOT_FOUND": "La restriccion operativa no existe.",
    "BUSINESS_PUBLICATION_HOLD_ALREADY_RELEASED": "La restriccion operativa ya fue liberada.",
    "OPERATION_REPORT_DUPLICATE": "Ya existe un reporte para esta operacion.",
    "OPERATION_REPORT_NOT_ALLOWED": "Esta operacion no puede reportarse en su estado actual.",
    "BUSINESS_OFFLINE": "El negocio no esta recibiendo nuevas ordenes.",
    "CAPACITY_AMOUNT_INVALID": "Revisa el monto disponible indicado.",
    "BUSINESS_CAPACITY_BELOW_RESERVED": "El monto disponible no puede quedar por debajo de lo reservado.",
    "BUSINESS_CAPACITY_BELOW_ACTIVE_ADS": "Pausa o ajusta tus anuncios activos, o termina las negociaciones abiertas, antes de bajar el disponible.",
    "BUSINESS_CAPACITY_INSUFFICIENT": "El negocio ya no puede cubrir este monto.",
    "BUSINESS_DAILY_LIMIT_EXCEEDED": "El negocio alcanzo su limite operativo diario.",
    "BUSINESS_CAPACITY_RESERVATION_CONFLICT": "No se pudo reservar la capacidad para esta orden.",
    "SURFACE_ACCESS_DENIED": "No tienes acceso a esta superficie de NODO.",
    "BUSINESS_ACCESS_LINK_REQUIRED": "Este usuario no tiene un vinculo activo con el negocio.",
    "BUSINESS_ACCESS_SUSPENDED": "El acceso de esta persona al negocio esta suspendido.",
    "BUSINESS_ACCESS_BLOCKED": "El acceso de esta persona al negocio esta bloqueado.",
    "BUSINESS_ACCESS_REVOKED": "El acceso de esta persona al negocio fue revocado.",
    "BUSINESS_SUSPENDED": "El negocio esta suspendido temporalmente.",
    "BUSINESS_BLOCKED": "El negocio esta bloqueado.",
    "USER_BLOCKED": "Este usuario esta bloqueado.",
    "USER_NOT_ACTIVE": "Este usuario no esta activo.",
    "USER_STATUS_INVALID": "El estado del usuario no permite esta accion.",
    "USER_STATUS_TRANSITION_INVALID": "La transicion de estado del usuario no esta permitida.",
    "USER_STATUS_MUTATION_NOT_ALLOWED": "No tienes permiso para modificar ese usuario.",
    "LAST_SUPER_ADMIN_REQUIRED": "Debe quedar al menos un super_admin activo.",
    "BUSINESS_ACCESS_LINK_NOT_FOUND": "No encontramos el vinculo de acceso solicitado.",
    "BUSINESS_PIN_NOT_SET": "Crea tu PIN para proteger esta accion.",
    "BUSINESS_PIN_REQUIRED": "Desbloquea tu PIN para completar esta accion.",
    "BUSINESS_PIN_LOCKED": "Tu PIN esta bloqueado temporalmente. Intenta de nuevo mas tarde.",
    "BUSINESS_PIN_INVALID": "PIN incorrecto.",
    "BUSINESS_INTAKE_NOT_FOUND": "No encontramos esta solicitud.",
    "BUSINESS_INTAKE_STATUS_INVALID": "El estado de la solicitud no permite esta accion.",
    "BUSINESS_INTAKE_ALREADY_ACCEPTED": "Esta solicitud ya fue aceptada.",
    "BUSINESS_INTAKE_INCOMPLETE": "La solicitud no tiene informacion suficiente para aprobar el negocio.",
    "ADMIN_CASE_FILE_ANCHOR_INVALID": "La pista de investigacion no es valida.",
    "ADMIN_CASE_FILE_ANCHOR_NOT_FOUND": "No encontramos una ficha visible para esta pista.",
    "ADMIN_CASE_FILE_CURSOR_INVALID": "El cursor no corresponde a esta seccion de la ficha.",
    "ADMIN_CASE_FILE_SECTION_UNAVAILABLE": "Una seccion de la ficha no esta disponible temporalmente.",
    "BUSINESS_TELEGRAM_LINK_REQUIRED": "Debes asociar un Telegram ID valido.",
    "BOT_CONTACT_REQUIRED": "Debes compartir tu contacto de Telegram para continuar.",
    "BOT_INPUT_INVALID": "Revisa la respuesta enviada para continuar.",
    "BOT_UPLOAD_INVALID": "El archivo no cumple los requisitos.",
    "INVALID_PAYMENT_METHOD": "El metodo de pago no es valido.",
    "INVALID_DELIVERY_METHOD": "El metodo de entrega no es valido.",
    "PAYMENT_METHOD_NOT_APPROVED": "El metodo de pago no esta disponible para publicar.",
    "CREDIT_WALLET_NOT_FOUND": "No encontramos la billetera de creditos.",
    "CREDIT_BALANCE_INSUFFICIENT": "No hay creditos suficientes para publicar.",
    "IDEMPOTENCY_CONFLICT": "La llave de idempotencia ya fue usada con otro payload.",
    "ORDER_ALREADY_EXISTS": "Ya existe una orden para esta solicitud.",
    "ORDER_NOT_FOUND": "No encontramos la orden solicitada.",
    "ORDER_NOT_OWNED": "No encontramos la orden solicitada.",
    "ORDER_STATUS_INVALID": "El estado de la orden no permite esta accion.",
    "ORDER_STATE_CONFLICT": "La orden cambio mientras completabas la accion. Revisa su estado actual.",
    "RATING_NOT_ALLOWED": "Esta orden no se puede calificar en su estado actual.",
    "RATING_ALREADY_EXISTS": "Esta orden ya fue calificada.",
    "ORDER_EXPIRED": "La orden expiro antes de completar esta accion.",
    "ORDER_EXTENSION_ALREADY_USED": "Ya usaste la extension permitida para esta orden.",
    "ORDER_PAYMENT_NOT_SENT_CONFIRMATION_REQUIRED": "Confirma que no enviaste el pago antes de cancelar esta orden.",
    "ORDER_PAYMENT_ALREADY_REPORTED": "La orden ya tiene pago reportado.",
    "ORDER_PAYMENT_DETAILS_NOT_SHARED": "Espera a que el negocio comparta sus datos de pago en el chat.",
    "ORDER_PAYMENT_METHOD_UNAVAILABLE": "La orden no tiene una cuenta de pago disponible para compartir.",
    "NOTIFICATION_OUTBOX_UNAVAILABLE": "No pudimos crear la orden en este momento. Intenta nuevamente.",
    "ORDER_RECEIVER_DETAILS_INVALID": "Revisa los datos de Pago Movil antes de continuar.",
    "ORDER_RECEIVER_DETAILS_REQUIRED": "No encontramos datos estructurados de Pago Movil para esta accion.",
    "ORDER_RECEIVER_DETAILS_ALREADY_SHARED": "Los datos de Pago Movil de esta orden ya fueron compartidos y no pueden reemplazarse.",
    "ORDER_RECEIVER_DETAILS_NOT_FOUND": "No encontramos datos de Pago Movil compartidos para esta orden.",
    "ORDER_RECEIPT_CONFIRMATION_NOT_ALLOWED": "La orden no permite confirmar la recepcion en este estado.",
    "ORDER_COMPLETION_BLOCKED_BY_DISPUTE": "La orden tiene una disputa abierta y no puede completarse.",
    "PAYMENT_REPORT_NOT_ALLOWED": "La orden no permite reportar pago en este estado.",
    "PAYMENT_REPORT_NOT_FOUND": "No encontramos un reporte de pago pendiente para esta orden.",
    "PAYMENT_CONFIRMATION_NOT_ALLOWED": "La orden no permite confirmar pago en este estado.",
    "PAYMENT_REJECTION_NOT_ALLOWED": "Esta acción ya no está disponible. Reporta el problema con el pago para que NODO lo revise.",
    "DELIVERY_NOT_ALLOWED": "La orden no permite marcar entrega en este estado.",
    "PAYMENT_EVIDENCE_REQUIRED": "Debes subir el comprobante de pago para este metodo.",
    "PAYMENT_REPORT_ALREADY_SUBMITTED": "Esta orden ya tiene un reporte de pago enviado.",
    "PAYMENT_REPORT_AMOUNT_MISMATCH": "El monto reportado debe coincidir exactamente con el monto de la orden.",
    "PAYMENT_REPORT_PROOF_ALREADY_USED": "Ese comprobante ya fue usado en otra orden.",
    "INVALID_PAYMENT_EVIDENCE": "El comprobante de pago no cumple los requisitos.",
    "CREDIT_HOLD_NOT_FOUND": "No encontramos creditos bloqueados validos para esta orden.",
    "CREDIT_ALREADY_CONSUMED": "Los creditos de esta orden ya fueron consumidos.",
    "CREDIT_ALREADY_GRANTED": "Los creditos ya fueron acreditados.",
    "PURCHASE_NOT_FOUND": "No encontramos la compra de creditos.",
    "CREDIT_PURCHASE_NOT_FOUND": "No encontramos la compra de creditos.",
    "PURCHASE_STATUS_INVALID": "El estado de la compra no permite esta accion.",
    "INVALID_PACKAGE": "El paquete de creditos no es valido.",
    "CREDIT_PAYMENT_METHOD_DISABLED": "Este metodo de compra de creditos ya no esta disponible. Usa Base USDC.",
    "CRYPTO_PAYMENT_TX_HASH_NOT_ACCEPTED": "Este flujo no acepta tx hash manual. Actualiza la compra desde la app.",
    "CRYPTO_PAYMENT_PENDING_LIMIT_REACHED": "Ya tienes varias compras pendientes. Completa o cierra una antes de crear otra.",
    "CRYPTO_PAYMENT_PENDING_PURCHASE_EXISTS": "Ya tienes un pago Base USDC pendiente. Continualo o espera a que termine antes de crear otro.",
    "CRYPTO_PAYMENT_RATE_LIMIT_UNAVAILABLE": "No pudimos validar el limite de esta operacion. Intenta nuevamente.",
    "CREDIT_HANDOFF_NOT_FOUND": "No encontramos esta preparacion de wallet.",
    "CREDIT_HANDOFF_EXPIRED": "Esta preparacion de wallet vencio. Inicia una nueva desde Telegram.",
    "CREDIT_HANDOFF_ALREADY_USED": "Esta preparacion de wallet ya fue utilizada.",
    "CREDIT_HANDOFF_NETWORK_INVALID": "Cambia tu wallet a Base para continuar.",
    "CREDIT_HANDOFF_SIGNATURE_INVALID": "No pudimos comprobar el control de esta wallet.",
    "CREDIT_HANDOFF_UNAVAILABLE": "No pudimos preparar la conexion de wallet. Intenta nuevamente.",
    "STRIPE_SIGNATURE_INVALID": "No pudimos validar la firma de Stripe.",
    "STRIPE_WEBHOOK_DUPLICATE": "El evento de Stripe ya fue procesado.",
    "STRIPE_SESSION_INVALID": "No pudimos validar la sesion de Stripe.",
    "ONCHAIN_RECEIVING_WALLET_NOT_CONFIGURED": "La wallet de recepcion BASE no esta configurada correctamente.",
    "ONCHAIN_TOKEN_NOT_ALLOWED": "Ese token no esta disponible para comprar creditos.",
    "ONCHAIN_RPC_UNAVAILABLE": "No pudimos consultar la red Base. Intenta nuevamente.",
    "ONCHAIN_TX_INVALID": "El tx hash no es valido.",
    "ONCHAIN_TX_NOT_FOUND": "No encontramos esa transaccion en Base.",
    "ONCHAIN_TX_ALREADY_USED": "Esta transaccion ya fue usada.",
    "ONCHAIN_VERIFICATION_FAILED": "No pudimos verificar la transaccion.",
    "MANUAL_PAYMENT_PROOF_REQUIRED": "Debes subir un comprobante valido.",
    "MANUAL_PAYMENT_ALREADY_REVIEWED": "Esta compra manual ya fue revisada.",
    "REFERRAL_NOT_ALLOWED": "No puedes aplicar este referido.",
    "REFERRAL_ALREADY_USED": "Este referido ya fue usado.",
    "REFERRAL_CODE_NOT_FOUND": "No encontramos el codigo de referido.",
    "REFERRAL_CAP_REACHED": "El limite de creditos por referidos fue alcanzado.",
    "FOUNDER_ACCESS_EXPIRED": "El acceso founder ya expiro.",
    "DISPUTE_NOT_FOUND": "No encontramos la disputa solicitada.",
    "DISPUTE_ALREADY_OPEN": "Ya existe una disputa abierta para esta orden.",
    "DISPUTE_NOT_ALLOWED": "La orden no permite abrir una disputa en este estado.",
    "DISPUTE_STATUS_INVALID": "El estado de la disputa no permite esta accion.",
    "DISPUTE_REASON_REQUIRED": "Debes indicar un motivo de disputa valido.",
    "DISPUTE_RESOLUTION_NOT_ALLOWED": "La disputa no permite esta resolucion.",
    "DISPUTE_RESOLUTION_REASON_REQUIRED": "Debes indicar una razon para resolver la disputa.",
    "MESSAGE_ATTACHMENT_INVALID": "El adjunto no cumple los requisitos.",
    "MESSAGE_ATTACHMENT_NOT_FOUND": "No encontramos ese adjunto.",
    "MESSAGE_BODY_REQUIRED": "Debes escribir un mensaje.",
    "MESSAGE_ATTACHMENT_TYPE_NOT_ALLOWED": "El tipo de adjunto no esta permitido.",
    "MESSAGE_ATTACHMENT_TOO_LARGE": "El adjunto supera el tamano permitido.",
    "SUPPORT_TICKET_NOT_FOUND": "No encontramos el ticket solicitado.",
    "SUPPORT_TICKET_STATUS_INVALID": "El estado del ticket no permite esta accion.",
    "SUPPORT_SCOPE_INVALID": "El tipo de soporte no esta permitido.",
    "SUPPORT_CATEGORY_INVALID": "La categoria de soporte no es valida.",
    "SUPPORT_ESCALATION_NOT_ALLOWED": "Este ticket no puede escalarse en este momento.",
    "SUPPORT_MESSAGE_REQUIRED": "Debes escribir un mensaje de soporte.",
    "SUPPORT_ATTACHMENT_INVALID": "El adjunto de soporte no cumple los requisitos.",
    "SUPPORT_ATTACHMENT_TOO_LARGE": "El adjunto de soporte supera el tamano permitido.",
    "SUPPORT_ATTACHMENT_TYPE_NOT_ALLOWED": "El tipo de adjunto de soporte no esta permitido.",
    "SUPPORT_ATTACHMENT_NOT_FOUND": "No encontramos el adjunto solicitado.",
    "SUPPORT_ATTACHMENT_ACCESS_DENIED": "No tienes permiso para ver ese adjunto.",
    "SUPPORT_ASSIGNMENT_NOT_ALLOWED": "No puedes asignar este ticket.",
    "SUPPORT_ASSIGNEE_INVALID": "El usuario asignado no puede recibir tickets de soporte.",
    "JOB_LOCK_NOT_ACQUIRED": "Otro proceso esta ejecutando este job.",
    "JOB_RUN_ALREADY_ACTIVE": "Ya existe una ejecucion activa para este job.",
    "JOB_NOT_FOUND": "No encontramos la ejecucion del job solicitada.",
    "JOB_CONFIG_INVALID": "La configuracion del job no es valida.",
    "ORDER_STATE_CHANGED_DURING_JOB": "La orden cambio de estado durante el procesamiento.",
    "CREDIT_RELEASE_FAILED": "No se pudo liberar el hold de creditos. La operacion no se completo.",
    "NOTIFICATION_SEND_FAILED": "No se pudo enviar una notificacion temporalmente.",
    "TELEGRAM_RATE_LIMITED": "El canal de notificaciones esta limitado temporalmente.",
    "TELEGRAM_BOT_NOT_CONFIGURED": "El bot de Telegram no esta configurado.",
    "TELEGRAM_BOT_SEND_FAILED": "No pudimos enviar el mensaje de Telegram.",
    "AUTO_COMPLETE_BLOCKED_BY_DISPUTE": "La orden no puede completarse automaticamente porque tiene disputa abierta.",
    "SENSITIVE_EXPORT_BLOCKED": "La exportacion de datos sensibles no esta permitida.",
    "OBSERVABILITY_DISABLED": "La recoleccion de diagnostico no esta habilitada.",
    "OBSERVABILITY_EVENT_INVALID": "El evento de diagnostico no cumple el contrato.",
    "OBSERVABILITY_EVENT_TOO_LARGE": "El evento de diagnostico supera el tamano permitido.",
    "OBSERVABILITY_BATCH_TOO_LARGE": "La cantidad de eventos de diagnostico supera el limite permitido.",
    "OBSERVABILITY_RATE_LIMITED": "Demasiados eventos de diagnostico. Intenta nuevamente en un momento.",
    "OBSERVABILITY_ACCESS_DENIED": "No tienes permiso para enviar diagnostico de esta superficie.",
    "NOT_FOUND": "No encontramos el recurso solicitado.",
    "STORAGE_UPLOAD_FAILED": "No logramos guardar el comprobante privado.",
    "AMOUNT_OUT_OF_RANGE": "El monto esta fuera del rango permitido.",
    "ORDER_QUOTE_CHANGED": "La tasa cambio. Revisa la cotizacion antes de confirmar.",
    "STATE_TRANSITION_NOT_ALLOWED": "La transicion de estado no esta permitida.",
    "INTERNAL_ERROR": "Ocurrio un error temporal.",
}


class ApiError(RuntimeError):
    def __init__(self, code: str, message: str | None = None, status_code: int = 400) -> None:
        self.code = code
        self.message = message or ERROR_MESSAGES.get(code, "No pudimos completar la accion.")
        self.status_code = status_code
        super().__init__(self.message)


def error_payload(code: str, message: str, request_id: str, details: dict | None = None) -> dict:
    return {
        "error": {
            "code": code,
            "message": message,
            "details": details or {},
        },
        "request_id": request_id,
    }


def api_error_response(code: str, message: str, request_id: str, status_code: int, headers: dict[str, str] | None = None) -> object:
    from fastapi.responses import JSONResponse

    response_headers = {"X-NODO-Error-Code": code, "X-Request-Id": request_id}
    if headers:
        response_headers.update(headers)
    return JSONResponse(status_code=status_code, content=error_payload(code, message, request_id), headers=response_headers)
